helloWorld: helloWorldThread.cc
	g++ --std=c++11 -pthread helloWorldThread.cc -o helloWorld
mutex: mutex.cc
	g++ --std=c++11 -pthread mutex.cc -o mutex
template: template.h
	g++ template.cc -o template
clean:
	rm mutex helloWorld

